---
- name: "Searching for apt preferences files not managed by us"
  become: true
  changed_when: false
  find:
    paths: "/etc/apt/preferences.d"
    file_type: "file"
    excludes:
      - "mozilla"
      - "google"
      - "docker"
      - "i3wm"
      - "1password"
      - "virtualbox"
      - "alacritty"
      - "signal"
      - "tailscale"
  register: "apt_prefs_found_files"

- name: "Delete apt preferences files not managed by us"
  become: true
  file:
    path: "{{ item.path }}"
    state: "absent"
  with_items: "{{ apt_prefs_found_files['files'] }}"
  notify: 'linux_apt-get-update'

- name: "Searching for apt list files not managed by us"
  become: true
  changed_when: false
  find:
    paths: "/etc/apt/sources.list.d"
    file_type: "file"
    excludes: 
      - "ubuntu-base.list"
      - "google.sources"
      - "docker.sources"
      - "i3wm.list"
      - "virtualbox.sources"
      - "alacritty.sources"
      - "1password.sources"
      - "graphics-drivers.sources"
      - "mozilla.sources"
      - "signal.sources"
      - "tailscale.sources"
  register: "apt_found_files"

- name: "Delete apt list files not managed by us"
  become: true
  file:
    path: "{{ item.path }}"
    state: "absent"
  with_items: "{{ apt_found_files['files'] }}"
  notify: 'linux_apt-get-update'

- name: "Searching for xorg conf files not managed by us"
  become: true
  changed_when: false
  find:
    paths: "/etc/X11/xorg.conf.d"
    file_type: "file"
    excludes:
      - "60-magictrackpad.conf"
      - "70-optical-mice.conf"
      - "99-M570Logitech.conf"
  register: "xorg_found_files"

- name: "Delete xorg conf files not managed by us"
  become: true
  file:
    path: "{{ item.path }}"
    state: "absent"
  with_items: "{{ xorg_found_files['files'] }}"

- name: "Searching for sudoers files not managed by us"
  become: true
  changed_when: false
  find:
    paths: "/etc/sudoers.d"
    file_type: "file"
    excludes:
      - "README"
      - "00-marvin"
  register: "sudoers_found_files"

- name: "Delete sudoers files not managed by us"
  become: true
  file:
    path: "{{ item.path }}"
    state: "absent"
  with_items: "{{ sudoers_found_files['files'] }}"

- meta: flush_handlers
