---
- include_tasks: "apt_repos.yml"
- include_tasks: "sshd.yml"
- include_tasks: "grub.yml"
- include_tasks: "sudoers.yml"
- include_tasks: "programs.yml"
- include_tasks: "i3wm.yml"
- include_tasks: "x11.yml"
- include_tasks: "fonts.yml"
- include_tasks: "browsers.yml"
- include_tasks: "docker.yml"
- include_tasks: "user.yml"
- include_tasks: "ergodox.yml"
- include_tasks: "hostname.yml"
- include_tasks: "nvidia.yml"
- include_tasks: "rng_tools.yml"
- include_tasks: "rofi.yml"
- include_tasks: "virtualbox.yml"
- include_tasks: "yubikey.yml"
- include_tasks: "alacritty.yml"
- include_tasks: "1password.yml"
- include_tasks: "snapd.yml"
- include_tasks: "clear_unmanaged_files.yml"
