---
- name: "Add marvinpinto/kitchensink as a tap"
  become: true
  become_user: "marvin"
  community.general.homebrew_tap:
    name: "marvinpinto/kitchensink"
    url: "https://github.com/marvinpinto/kitchensink.git"

- name: "Install all the homebrew managed apps"
  become: true
  become_user: "marvin"
  community.general.homebrew:
    name:
      - "aws-vault"
      - "cheat"
      - "fzf"
      - "git"
      - "ansible"
      - "git-lfs"
    state: "present"
    path: "/home/linuxbrew/.linuxbrew/bin"

- name: "Install all the homebrew managed apps"
  become: true
  become_user: "marvin"
  community.general.homebrew:
    name:
      - "mkcert"
      - "neovim"
      - "rclone"
      - "jq"
      - "git-delta"
      - "tree"
    state: "present"
    path: "/home/linuxbrew/.linuxbrew/bin"

- name: "Install all the homebrew managed apps"
  become: true
  become_user: "marvin"
  community.general.homebrew:
    name:
      - "the_silver_searcher"
      - "python"
      - "iftop"
      - "htop"
      - "xclip"
      - "tmux"
    state: "present"
    path: "/home/linuxbrew/.linuxbrew/bin"

- name: "Install all the homebrew managed apps"
  become: true
  become_user: "marvin"
  community.general.homebrew:
    name:
      - "tmuxinator"
      - "age"
      - "restic"
      - "tio"
    state: "present"
    path: "/home/linuxbrew/.linuxbrew/bin"

- name: "Install base Ubuntu programs"
  become: true
  apt:
    name:
      - "lightdm"
      - "vim-gtk"
      - "tmux"
      - "scrot"
      - "imagemagick"
      - "xautolock"
      - "whois"
      - "touchegg"
      - "linux-generic"
      - "xournal"
      - "audacity"
      - "default-jre"
      - "cpulimit"
      - "language-pack-en-base"
      - "tzdata"
      - "ca-certificates"
      - "net-tools"
      - "simple-scan"
      - "traceroute"
      - "pdfarranger"  # useful utility for adding/removing pdf pages, etc
      - "gimp"
      - "gnome-clocks"
      - "ffmpeg"
      - "gnome-screenshot"
      - "vlc"
    state: "present"

- name: "Remove a few things I do not care for"
  become: true
  apt:
    name:
      - "avahi-daemon"
      - "apport"
      - "libreoffice-base-core"
      - "rhythmbox"
      - "thunderbird"
      - "empathy"
      - "duplicity"
      - "friends"
      - "remmina"
      - "shotwell"
      - "shotwell-common"
      - "telepathy-gabble"
      - "telepathy-haze"
      - "telepathy-idle"
      - "telepathy-indicator"
      - "telepathy-logger"
      - "telepathy-mission-control-5"
      - "totem"
      - "libreoffice-*"
      - "flashplugin-installer"
      - "evince"
      - "evince-common"
      - "brltty"
      - "cups-browsed"
      - "speech-dispatcher"
      - "command-not-found"
    state: "absent"
    purge: "yes"

- name: "Update the imagemagick config file"
  become: true
  copy:
    src: "imagemagick-policy.xml"
    dest: "/etc/ImageMagick-6/policy.xml"
    owner: "root"
    group: "root"
    mode: "0644"
